services:
  - name: backend
    path: backend
    dockerfile: Dockerfile

  - name: auth-service
    path: auth-service
    dockerfile: Dockerfile

  - name: frontend
    path: frontend
    dockerfile: Dockerfile
